### ISSUE TITLE
Publish chart somewhere

### ISSUE THREAD

**Issue by genebean** [lightstep/lightstep-satellite-helm-chart#1]
This chart not being published and merges not updating the chart version make it extremely difficult for a user to track upstream changes. This is a request to publish the chart somewhere. This could be done via something like https://github.com/helm/chart-releaser. There is a full example of this in https://dev.to/jamiemagee/how-to-host-your-helm-chart-repository-on-github-3kd

**Comment by AjohnsonLS** [comment]
This is a great note, and I'm looking into fixing this.  Thanks for bringing this up

**Comment by AjohnsonLS** [comment]
PR for adding to Helm hub: https://github.com/helm/hub/pull/443

**Comment by genebean** [comment]
Yay!

**Comment by AjohnsonLS** [comment]
Available here: https://artifacthub.io/packages/helm/lightstepsatellite/lightstep

Pending on the helm hub as well.
