### ISSUE TITLE
Ingress Service Port Template Error

### ISSUE THREAD

**Issue by SamKirsch10** [lightstep/lightstep-satellite-helm-chart#12]
Hey guys,

Looks like `.Values.service.port` in the [ingress file](https://github.com/lightstep/lightstep-satellite-helm-chart/blob/master/charts/lightstepsatellite/templates/ingress.yaml#L3) is incorrect as per the defaults [here for the service map](https://github.com/lightstep/lightstep-satellite-helm-chart/blob/master/charts/lightstepsatellite/values.yaml#L41). Can we get one switched so we can use the defaults and not have to override?

thanks

**Comment by AjohnsonLS** [comment]
https://github.com/lightstep/lightstep-satellite-helm-chart/commit/9b9ca45ade1fd4a731a5b65ee8d146bbd9ca5f54

This should address that. Thanks for pointing it out.
