### ISSUE TITLE
API Key env variable

### ISSUE THREAD

**Issue by SamKirsch10** [lightstep/lightstep-satellite-helm-chart#13]
It seems the deployment.yaml is using the wrong environment variable name...

- [here](https://github.com/lightstep/lightstep-satellite-helm-chart/blob/master/charts/lightstepsatellite/templates/deployment.yaml#L37) -> COLLECTOR_API_KEY 
- [here](https://github.com/lightstep/lightstep-satellite-helm-chart/blob/master/charts/lightstepsatellite/templates/deployment.yaml#L44) -> COLLECTOR_API_KEY

**Comment by AjohnsonLS** [comment]
Is this causing an issue for you? Per the documentation (https://docs.lightstep.com/docs/satellite-configuration-parameters#satellite_key) in the docker env vars, this should be correct.

**Comment by AjohnsonLS** [comment]
Closing unless this is blocking or causing any problems.
