### ISSUE TITLE
v1.2.0 breaks deployment if statsd is enabled

### ISSUE THREAD

**Issue by genebean** [lightstep/lightstep-satellite-helm-chart#17]
Version 1.2.0 changed the name of the statsd configmap but did not update this:

https://github.com/lightstep/lightstep-satellite-helm-chart/blob/a92595f672315658dee81dd6585ec9faa4e9ed08/charts/lightstepsatellite/templates/deployment.yaml#L200-L206

As a result, the chart is now broken and does not deploy.

**Comment by genebean** [comment]
FWIW, I think changing the name of the configmap was a bad idea and should be reverted

**Comment by AjohnsonLS** [comment]
Closing this ticket as v1.2.1 should address this. The configMap was changed to better allow side by side deployments.
