### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by genebean** [lightstep/lightstep-satellite-helm-chart#4]
It would be really helpful if this supported Prometheus metrics as opposed to only statsd.

**Comment by andrewcheelightstep** [comment]
Closing this issue because this is available here: https://docs.lightstep.com/updates/satellite-prometheus

**Comment by genebean** [comment]
I respectfully disagree. That page lists a partial attempt at a workaround. I’m asking for either native Prometheus metrics or something included in this chart that actually works in conjunction with the settings in values.yaml and implements labels for more than the project. 

I’ll be happy to share my mapping once I’m done with it as a stopgap to native Prometheus.
