### ISSUE TITLE
Cleanup chart

### ISSUE THREAD

**Issue by mattfarina** [lightstep/lightstep-satellite-helm-chart#7]
There's [a pull request to add the chart to the Helm Hub](https://github.com/helm/hub/pull/443) but this chart is doing to have some issues displaying in Hubs.

Two immediate issues come to mind...

1. The `version` in the `Chart.yaml` file is `1.0`. In YAML this is a float64. Helm uses semantic versions and this isn't valid semver. Update the version to be `1.0.0`. This will be read as a string and be in semver format.
2. The icon is a file pointer. The Hubs are looking for a URI reference to a remote locations like a https URL. They aren't able to pull the image from the chart for display. I would suggest pointing right to the logo as a non-file URL

To catch some of these issues you might consider running `helm lint` as part of your CI processes.

**Comment by AjohnsonLS** [comment]
Thanks for bringing these up.  Both of these issues should be addressed.

**Comment by mattfarina** [comment]
@AjohnsonLS great. you might want to re-generate the Helm repository index.yaml file so that pulls in the new information.

**Comment by AjohnsonLS** [comment]
Perfect, done and committed. Thank you for the guidance
